### PR TITLE
Fixed localhost redis connection on caching unit test

### PR DESCRIPTION
**Pull request by dughetti**
@lsvx , @maxicecilia There was a local connection to redis on caching unit test. I solved this by taking the config from adapter.

### CODE REVIEW

**Comment by lsvx** [comment]
Cool. This looks fine. Was there an error before?

**Comment by dughetti** [comment]
:+1:  Steven Sierra from CI told me that he had some problems trying to run the tests without a local redis-server installed. And I found that the caching file was generating a local connection (redis.createClient() creates a local redis connection by default)

**Comment by lsvx** [comment]
Ah, ok so what you did was make the redis connection in the caching test file configurable. That's great. Please explain it in the pull request next time. The purpose of this branch was not clear from your text

**Comment by maxicecilia** [comment]
+1

**Pull request merged**
